### PR TITLE
cconsole.log in output for docker

### LINKED ISSUE #1: cconsole.log as logs for docker
when I starting container it would be good, if I may see what's going wrong by looking at cconsole.log content in docker's logs.

### PR DESCRIPTION
**Pull request by daimor**
added -cconsole boolean flag if needs to see what shows in cconsole.log in docker logs
docker run -ti imageid -cconsole
closes #1

### CODE REVIEW

**Comment by zrml** [comment]
@daimor Excellent idea!
I love to see this.
Apologies for my delay in answering. I'm now worried I did not see a notification...

OK Let's add it! This is cool, th ecode is clean and thanks for maintaining GO idiom and errors etc. 
Thank you for your precious collaboration!

**Comment by daimor** [comment]
It was my first experience with GO, I never coded on it before. :)

**Comment by zrml** [comment]
@daimor cool!
:-)
I like the language for several reasons.
Anyway: your output goes to the container std output right? Have you tested it? Like in
$ docker logs <container_id>
right?

**Comment by daimor** [comment]
Yes, docker logs now shows cconsole.log if -cconsole flag was defined
and I tested it, and it is my flag by default now

**Pull request merged**
